version: "3.8"
services:
  backend:
    build: ./server-api
    container_name: mern-backend
    ports:
      - "3005:3005"
    networks:
      - mern-network

  frontend:
    build: ./final-app
    container_name: mern-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
